[default]
DEBUG = false
TITLE = "@rdrgzbhnng"
HEADLINE1 = "I am a UX Designer specialised in Interaction Design with an enthusiastic focus on the Human-Centered Design."
HEADLINE2 = "I like the quiet life and beautiful things, less but better. I appreciate sincere people and I hate mediocre and confusing stuff."
BYE = "Hope to see you soon,"
SIGNATURE = "Carlos Alberto Rodriguez Behning"
